#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
# auto_completion_tab_key_behavior = "complete"

[[layers]]
name = 'defult'

[[layers]]
name = 'format'
format_on_save = true

[[layers]]
name = 'colorscheme'

# add custom_plugins: https://github.com/mhartington/oceanic-next
[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0

# add custom_plugins: https://github.com/ayu-theme/ayu-vim
[[custom_plugins]]
  repo = "ayu-theme/ayu-vim"
  merged = 0

# add custom_plugins: https://github.com/prettier/vim-prettier
[[custom_plugins]]
  repo = "prettier/vim-prettier"
  merged = 0

# The lsp layer has to be enabled too. SpaceVim converts the configuration in the lsp layer and then passes it to coc.
# You can put your language servers here.
[[layers]] 
  name = 'lsp'
  filetypes = [
    'javascript',
    'typescript',
    'python',
    'html',
    'css',
    'rust'
  ]

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'git'


[[layers]]
name = 'lang#javascript'
format_on_save = true

[[layers]]
name = 'lang#typescript'
#typescript_server_path = '/home/joaquingumuciol/.yarn/bin/tsserver'
format_on_save = true

[[layers]]
name = 'lang#javascript'
format_on_save = true

[[layers]]
name = 'lang#html'
format_on_save = true

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'
format_on_save = true

[[layers]]
name = 'lang#dart'
format_on_save = true

[[layers]]
name = 'fzf'

[[layers]]
name = 'tool#zeal'






